<?php

/**
 * Regenerates the Composer classmap after PHP-Scoper has scoped vendor files.
 *
 * PHP-Scoper modifies namespace declarations in PHP files but cannot reliably update Composer's autoloader because classmap files are enormous single-line arrays and entries get dropped. This script scans all PHP files under vendor/, extracts the actual declared class/interface/trait/enum names, and rewrites both autoload_classmap.php and the $classMap in autoload_static.php.
 */

$baseDir = $argv[1] ?? getcwd();
$vendorDir = $baseDir . '/vendor';
$classMap = [];

$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($vendorDir, FilesystemIterator::SKIP_DOTS)
);

foreach ($iterator as $file) {
    if ($file->getExtension() !== 'php') {
        continue;
    }

    $path = $file->getPathname();
    $relPath = substr($path, strlen($vendorDir) + 1);

    if (str_contains($relPath, '/Tests/') ||
        str_contains($relPath, '/tests/') ||
        str_contains($relPath, '/Test/') ||
        str_contains($relPath, '/test/')) {
        continue;
    }
    // Skip Composer autoloader internals (ClassLoader, autoload_*, etc.) but keep InstalledVersions which is referenced by auto-instrumentation packages.
    if (str_starts_with($relPath, 'composer/') && !str_contains($relPath, 'InstalledVersions')) {
        continue;
    }

    $content = file_get_contents($path);
    if ($content === false) {
        continue;
    }

    $namespace = '';
    if (preg_match('/^\s*namespace\s+([^;{]+)/m', $content, $m)) {
        $namespace = trim($m[1]) . '\\';
    }

    if (preg_match_all('/^\s*(?:abstract\s+|final\s+|readonly\s+)*(?:class|interface|trait|enum)\s+(\w+)/m', $content, $matches)) {
        foreach ($matches[1] as $className) {
            $fqcn = $namespace . $className;
            $classMap[$fqcn] = $relPath;
        }
    }
}

ksort($classMap);
echo "Generated classmap with " . count($classMap) . " entries\n";

// Write autoload_classmap.php
$lines = ["<?php\n\n// autoload_classmap.php @generated by build-classmap.php\n\n",
    "\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\n",
    "return array(\n"];
foreach ($classMap as $class => $path) {
    $lines[] = "    " . var_export($class, true) . " => \$vendorDir . '/" . $path . "',\n";
}
$lines[] = ");\n";
file_put_contents($vendorDir . '/composer/autoload_classmap.php', implode('', $lines));

// Update autoload_static.php: replace the $classMap array
$staticFile = $vendorDir . '/composer/autoload_static.php';
$staticContent = file_get_contents($staticFile);
if ($staticContent === false) {
    echo "Warning: could not read autoload_static.php\n";
    exit(0);
}

$mapEntries = [];
foreach ($classMap as $class => $path) {
    $escapedClass = str_replace('\\', '\\\\', $class);
    $mapEntries[] = "'{$escapedClass}' => __DIR__ . '/..' . '/{$path}'";
}
$newClassMapBody = implode(', ', $mapEntries);

$start = strpos($staticContent, '$classMap = array');
if ($start !== false) {
    $arrayStart = strpos($staticContent, '(', $start + 17) + 1;
    $depth = 1;
    $pos = $arrayStart;
    while ($depth > 0 && $pos < strlen($staticContent)) {
        if ($staticContent[$pos] === '(') $depth++;
        if ($staticContent[$pos] === ')') $depth--;
        $pos++;
    }
    $arrayEnd = $pos - 1;
    $staticContent = substr($staticContent, 0, $arrayStart) . $newClassMapBody . substr($staticContent, $arrayEnd);
}

file_put_contents($staticFile, $staticContent);
echo "Updated autoload_static.php\n";

// Isolate the agent's autoload_files deduplication from the customer app's.
// Composer uses $GLOBALS['__composer_autoload_files'] to skip files already loaded by another autoloader. When the agent loads first (via auto_prepend_file), it marks file hashes as loaded. The app sees the same hashes and skips its own copies — but the agent loaded SCOPED versions, so global functions like \value() end up undefined. Using a separate global key prevents this entirely.
$realFile = $vendorDir . '/composer/autoload_real.php';
$realContent = file_get_contents($realFile);
$count = 0;
$realContent = str_replace('__composer_autoload_files', '__odigos_autoload_files', $realContent, $count);
file_put_contents($realFile, $realContent);
echo "Patched autoload_real.php: $count replacements (__composer_autoload_files -> __odigos_autoload_files)\n";

// Propagate excluded-namespace file hashes to __composer_autoload_files.
// The __odigos_autoload_files isolation above prevents the agent from marking hashes in the customer app's __composer_autoload_files. This is correct for scoped packages (different function names), but excluded-namespace packages declare the same functions/classes. Propagating their hashes tells the app's autoloader to skip them, preventing "Cannot redeclare" fatal errors.
$autoloadFilesPath = $vendorDir . '/composer/autoload_files.php';
if (file_exists($autoloadFilesPath)) {
    $filesContent = file_get_contents($autoloadFilesPath);
    preg_match_all(
        "/^\\s*'([a-f0-9]+)'\\s*=>\\s*\\\$(vendorDir|baseDir)\\s*\\.\\s*'([^']+)'/m",
        $filesContent,
        $fileMatches,
        PREG_SET_ORDER
    );

    $excludedHashes = [];
    foreach ($fileMatches as $fm) {
        $hash = $fm[1];
        $dir = $fm[2] === 'vendorDir' ? $vendorDir : $baseDir;
        $filePath = $dir . $fm[3];
        $src = @file_get_contents($filePath);
        if ($src === false) {
            continue;
        }
        if (!preg_match('/^\\s*namespace\\s+Odigos[\\s\\\\;{]/m', $src)) {
            $excludedHashes[] = $hash;
        }
    }

    if (!empty($excludedHashes)) {
        $entries = [];
        foreach ($excludedHashes as $h) {
            $entries[] = "            '$h' => true,";
        }

        $code = "        foreach (array(\n"
            . implode("\n", $entries) . "\n"
            . "        ) as \$h => \$v) {\n"
            . "            \$GLOBALS['__composer_autoload_files'][\$h] = \$v;\n"
            . "        }\n\n";

        $realContent = file_get_contents($realFile);
        $realContent = str_replace(
            '        return $loader;',
            $code . '        return $loader;',
            $realContent
        );
        file_put_contents($realFile, $realContent);
        echo "Injected " . count($excludedHashes) . " excluded-namespace hash(es) into autoload_real.php\n";
    } else {
        echo "No excluded-namespace file hashes to propagate\n";
    }
} else {
    echo "Warning: autoload_files.php not found\n";
}
